version: "3.8"

services:
  app:
    container_name: server-tic-tac-toe
    image: server-tic-tac-toe
    build:
      context: .
      target: development
    volumes:
      - ./src:/tic-tac-toe/src
    ports:
      - 4000:4000